### ISSUE TITLE
Suggested Improvements

### ISSUE THREAD

**Issue by gingerbeardman** [dg01d/bitbar-worldcup#2]
Cool plugin @dg01d 

I think it would be neater if it:
- showed only flags
- maybe with the names revealed as an alternate?
- used three letter ISO Country Codes  
- used fixed width monospaced font
- displayed time of kick-off for future games

eg.

`🇨🇴 0 – 0 🇯🇵`
`COL 0 – 0 JPN`

or at least to have things symmetrical

`COL 🇨🇴 0 – 0 🇯🇵 JPN`

**Comment by dg01d** [comment]
Yes, it does look better.

Merged your PR here, will do the same in the official repo

**Comment by gingerbeardman** [comment]
Couldn't figure out the alternate, I think it's broken in `bitbar-php`

Also a font-related bug needed to be fixed in `bitbar-php` so be sure to update that

**Comment by gingerbeardman** [comment]
Another PR coming soon with game running time and kick-off time
